
SELECT DISTINCT SMNPRODM_CO.NOTA,SMNPRODM_CO.NOME_BENEF,SMNPMIT.VLR_COBR,VLR_PGTO FROM SMNPRODM_CO
INNER JOIN SMNPRODM ON SMNPRODM.ID_SMNPRODM = SMNPRODM_CO.ID_SMNPRODM
INNER JOIN SMNPMIT ON SMNPMIT.ID_SMNPRODM = SMNPRODM.ID_SMNPRODM
INNER JOIN SCACONTR ON SCACONTR.ID_SCACONTR = SMNPRODM_CO.ID_SCACONTR
--LEFT JOIN #VW_PTU_A500_R504_80 ON #VW_PTU_A500_R504_80.R504_ID_SMNPRODM = SMNPRODM_CO.ID_SMNPRODM
WHERE SMNPRODM_CO.NOTA ='24032017'


SELECT DISTINCT SMNPRODM_CO.NOTA,SMNPRODM_CO.NOME_BENEF,SMNPMIT.VLR_COBR,VLR_PGTO FROM SMNPRODM_CO
INNER JOIN SMNPRODM ON SMNPRODM.ID_SMNPRODM = SMNPRODM_CO.ID_SMNPRODM
INNER JOIN SMNPMIT ON SMNPMIT.ID_SMNPRODM = SMNPRODM.ID_SMNPRODM
INNER JOIN SCACONTR ON SCACONTR.ID_SCACONTR = SMNPRODM_CO.ID_SCACONTR
--LEFT JOIN #VW_PTU_A500_R504_80 ON #VW_PTU_A500_R504_80.R504_ID_SMNPRODM = SMNPRODM_CO.ID_SMNPRODM
WHERE SMNPRODM_CO.NOTA ='240320177'



SELECT DISTINCT SMNPRODM_CO.NOTA,SMNPRODM_CO.NOME_BENEF,SGESERVI.DESCRICAO,SMNPMIT.VLR_COBR,VLR_PGTO FROM SMNPRODM_CO
INNER JOIN SMNPRODM ON SMNPRODM.ID_SMNPRODM = SMNPRODM_CO.ID_SMNPRODM
INNER JOIN SMNPMIT ON SMNPMIT.ID_SMNPRODM = SMNPRODM.ID_SMNPRODM
INNER JOIN SGESERVI ON SGESERVI.ID_SGESERVI = SMNPMIT.ID_SGESERVI
INNER JOIN SCACONTR ON SCACONTR.ID_SCACONTR = SMNPRODM_CO.ID_SCACONTR
WHERE SMNPRODM_CO.NOTA ='0420'
